repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: name-tests-test

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [
            "-rn", # Only display messages
            "-sn", # Don't display the score
          ]
        exclude: examples/

      - id: isort
        name: isort
        entry: isort .
        language: system
        types_or: [cython, pyi, python]
        require_serial: true

      - id: black
        name: black
        entry: black
        language: system
        types: [python]

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        exclude: tests/
        types: [python]

      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade
        language: system
        types: [python]
        args: [--py310-plus]
